In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
import pandas as pd
import numpy as np

In [3]:
data= pd.read_csv('data/Advertising.csv')
data

Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [4]:
a=np.array([[0, 1, 2], [3,4,5],[6, 7, 8]])
print(a)
# print(a.shape)
b=a[ : ,0:2]
c=a[0:2, 1]
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 4]


In [5]:
# pwd

In [6]:
# import pandas as pd

# # Load the dataset
# data = pd.read_csv('/content/drive/My Drive/data_code_DSCI6601/data/Advertising.csv')

# # Print the first few rows of the dataset
print(data.head(10))



   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9
5           6    8.7   48.9       75.0    7.2
6           7   57.5   32.8       23.5   11.8
7           8  120.2   19.6       11.6   13.2
8           9    8.6    2.1        1.0    4.8
9          10  199.8    2.6       21.2   10.6


In [7]:
data=data.drop(columns=['Unnamed: 0'])
print(data.head(10))


      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
5    8.7   48.9       75.0    7.2
6   57.5   32.8       23.5   11.8
7  120.2   19.6       11.6   13.2
8    8.6    2.1        1.0    4.8
9  199.8    2.6       21.2   10.6


In [8]:
rows, columns = data.shape

# Print the number of rows and columns
print("Number of rows:", rows)
print("Number of columns:", columns)


Number of rows: 200
Number of columns: 4


In [9]:
# !pip install --upgrade scikit-learn numpy

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [14]:
# Set all columns except the last as X and the last as Y
X = data.iloc[:, :-1]  # Select all columns except the last
y = data.iloc[:, -1]   # Select the last column


In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [16]:
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression()

In [17]:
# Coefficients and Intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)


Coefficients: [0.04472952 0.18919505 0.00276111]
Intercept: 2.9790673381226274


In [18]:
# Making predictions
y_pred = model.predict(X_test)

# Evaluating the model
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)


Mean Squared Error: 3.174097353976104
R-squared: 0.899438024100912


In [19]:
X_sample=X[0::3]
print(X.head(10))
print(X_sample.head(10))


      TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4
5    8.7   48.9       75.0
6   57.5   32.8       23.5
7  120.2   19.6       11.6
8    8.6    2.1        1.0
9  199.8    2.6       21.2
       TV  radio  newspaper
0   230.1   37.8       69.2
3   151.5   41.3       58.5
6    57.5   32.8       23.5
9   199.8    2.6       21.2
12   23.8   35.1       65.9
15  195.4   47.7       52.9
18   69.2   20.5       18.3
21  237.4    5.1       23.5
24   62.3   12.6       18.3
27  240.1   16.7       22.9


Build a model based on the column 'TV' only and compare the predictions with the original model.


In [20]:
X_tv = data.iloc[:, 0]  # Select all columns except the last
y_tv = data.iloc[:, -1]   # Select the last column

In [21]:
X_train_tv, X_test_tv, y_train_tv, y_test_tv = train_test_split(X_tv, y_tv, test_size=0.2, random_state=56)

In [22]:
model_tv = LinearRegression()
model.fit(X_train_tv.values.reshape(-1,1), y_train_tv)

LinearRegression()

In [23]:
# Coefficients and Intercept
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [0.04850469]
Intercept: 6.955378943325513


In [24]:
# Making predictions
y_pred_tv = model.predict(X_test_tv.values.reshape(-1,1))

In [25]:
# # Evaluating the model
mse = mean_squared_error(y_test_tv, y_pred_tv)
r2 = r2_score(y_test_tv, y_pred_tv)

In [26]:
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 9.315984465959882
R-squared: 0.6217272895900013


## TV AND RADIO

In [27]:
X_tv_radio = data.iloc[:,0:2]  # Select all columns except the last
y_tv_radio = data.iloc[:, -1]   # Select the last column

In [28]:
X_train_tv_radio, X_test_tv_radio, y_train_tv_radio, y_test_tv_radio = train_test_split(X_tv_radio, y_tv_radio, test_size=0.2, random_state=42)

In [29]:
model_tv_radio = LinearRegression()
model_tv_radio.fit(X_train_tv_radio, y_train_tv_radio)

LinearRegression()

In [30]:
# Coefficients and Intercept
print("Coefficients:", model_tv_radio.coef_)
print("Intercept:", model_tv_radio.intercept_)

Coefficients: [0.0447283  0.19066726]
Intercept: 3.028255250783305


In [31]:
y_pred_tv_radio = model_tv_radio.predict(X_test_tv_radio)

In [32]:
# # Evaluating the model
mse = mean_squared_error(y_test_tv_radio, y_pred_tv_radio)
r2 = r2_score(y_test_tv_radio, y_pred_tv_radio)

In [33]:
print("Mean Squared Error:", mse)
print("R-squared:", r2)

Mean Squared Error: 3.137948009068354
R-squared: 0.9005833101920356


#### with 20 samples

In [34]:
X_tv_radio = data.iloc[:20, :2]  # Select all columns except the last
y_tv_radio = data.iloc[:20, -1]   # Select the last column

X_train_tv_radio, X_test_tv_radio, y_train_tv_radio, y_test_tv_radio = train_test_split(X_tv_radio, y_tv_radio, test_size=0.2, random_state=42)

model_tv_radio = LinearRegression()
model_tv_radio.fit(X_train_tv_radio, y_train_tv_radio)

# Coefficients and Intercept
print("Coefficients:", model_tv_radio.coef_)
print("Intercept:", model_tv_radio.intercept_)

y_pred_tv_radio = model_tv_radio.predict(X_test_tv_radio)

# # Evaluating the model
mse = mean_squared_error(y_test_tv_radio, y_pred_tv_radio)
r2 = r2_score(y_test_tv_radio, y_pred_tv_radio)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Coefficients: [0.05013159 0.1298921 ]
Intercept: 3.6209374184096035
Mean Squared Error: 3.638050332386256
R-squared: 0.880295298253686


We noted that there is variation in terms of reported MSE and R2.
The conclusion is that the model is not stable.

Now with 40 samples

In [35]:
sampled_data = data.sample(40, random_state=42)

X_tv_radio = sampled_data.iloc[:40, :2]  # Select all columns except the last
y_tv_radio = sampled_data.iloc[:40, -1]   # Select the last column

X_train_tv_radio, X_test_tv_radio, y_train_tv_radio, y_test_tv_radio = train_test_split(X_tv_radio, y_tv_radio, test_size=0.2, random_state=42)

model_tv_radio = LinearRegression()
model_tv_radio.fit(X_train_tv_radio, y_train_tv_radio)

# Coefficients and Intercept
print("Coefficients:", model_tv_radio.coef_)
print("Intercept:", model_tv_radio.intercept_)

y_pred_tv_radio = model_tv_radio.predict(X_test_tv_radio)

# # Evaluating the model
mse = mean_squared_error(y_test_tv_radio, y_pred_tv_radio)
r2 = r2_score(y_test_tv_radio, y_pred_tv_radio)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

Coefficients: [0.04878942 0.16000597]
Intercept: 3.208989591169429
Mean Squared Error: 3.7221139984021567
R-squared: 0.8979875914722169


#### Taking Sample data and running num of iteration to calculate the variance

In [38]:
num_itr = 15000

mseScore = []
r2Score = []

for i in range(num_itr):
    sampled_data = data.sample(40, random_state=42)

    X = sampled_data.iloc[:, :-1]  # Select all columns except the last
    y = sampled_data.iloc[:, -1]   # Select the last column

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= np.random.randint(1000))

    model = LinearRegression()
    model.fit(X_train, y_train)

    # Coefficients and Intercept
    # print("Coefficients:", model_tv_radio.coef_)
    # print("Intercept:", model_tv_radio.intercept_)

    y_pred = model.predict(X_test)

    # # Evaluating the model
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    print("Iteration:", i)
    print("Mean Squared Error:", mse)
    print("R-squared:", r2)
    print("--------------------------")

    #Collecting values
    mseScore.append(mse)
    r2Score.append(r2)

print("Average Mean Squared Error:", np.mean(mseScore))
print("Std of Mean Squared Error:", np.std(mseScore))
print("Average R2 Score:", np.mean(r2Score))
print("Std of R2 Score:", np.std(r2Score))


Iteration: 0
Mean Squared Error: 3.489781260411112
R-squared: 0.8707697822885694
--------------------------
Iteration: 1
Mean Squared Error: 2.247110353416298
R-squared: 0.8560222425153993
--------------------------
Iteration: 2
Mean Squared Error: 3.9719254078032216
R-squared: 0.8798366204835752
--------------------------
Iteration: 3
Mean Squared Error: 6.351171292695899
R-squared: 0.8562346498549747
--------------------------
Iteration: 4
Mean Squared Error: 2.5543467580306847
R-squared: 0.8953773047173121
--------------------------
Iteration: 5
Mean Squared Error: 2.10910533180611
R-squared: 0.9487956947849937
--------------------------
Iteration: 6
Mean Squared Error: 7.400553696620089
R-squared: 0.672340255976309
--------------------------
Iteration: 7
Mean Squared Error: 4.099582572573047
R-squared: 0.8893905809505306
--------------------------
Iteration: 8
Mean Squared Error: 2.8044945009319457
R-squared: 0.9083942899126524
--------------------------
Iteration: 9
Mean Squared E

In [40]:
X1 = X_train
y1 = y_train

# Add intercapt term
X1 = np.c_[X1, np.ones(X1.shape[0])]

# convert to numpy arrays
X1 = np.array(X1)
y1 = np.array(y1)

betaHat = np.linalg.inv(X1.T @ X1) @ (X1.T @ y1)

#Output terms
print("Coefficient:", betaHat)

Coefficient: [ 0.04686     0.19884328 -0.02279707  3.33327705]
